# Generated by Django 3.0.6 on 2020-06-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homescreen', '0002_auto_20200606_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.IntegerField(max_length=2847)),
            ],
        ),
    ]
