# Generated by Django 3.0.6 on 2020-06-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homescreen', '0003_backgroundimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundimage',
            name='img_url',
            field=models.CharField(max_length=2847),
        ),
        migrations.AlterField(
            model_name='blog',
            name='post_num',
            field=models.IntegerField(),
        ),
    ]
