# Generated by Django 3.0.6 on 2020-06-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homescreen', '0004_auto_20200607_0732'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImageHomescreen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.CharField(max_length=2847)),
            ],
        ),
        migrations.DeleteModel(
            name='BackgroundImage',
        ),
    ]
