# Generated by Django 3.0.6 on 2020-06-07 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homescreen', '0006_auto_20200607_0734'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackgroundImageHome',
        ),
    ]
