# Generated by Django 3.0.6 on 2020-06-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YourBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('image_url', models.CharField(max_length=2844)),
                ('des', models.TextField(max_length=5000)),
            ],
        ),
    ]
